# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coord_x', models.FloatField(default=0.0)),
                ('coord_y', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Classroom', max_length=100)),
                ('capacity', models.IntegerField()),
                ('max_ta', models.PositiveIntegerField(verbose_name='Max Assignable TAs')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Building')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
            },
        ),
        migrations.CreateModel(
            name='ClassroomSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Classroom')),
            ],
            options={
                'verbose_name': 'Classroom Schedule',
                'verbose_name_plural': 'Classroom Schedules',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Course Code')),
                ('capacity', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Building')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('Midterm', 'MIDTERM'), ('Final', 'FINAL')], default='Midterm', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Building')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course', verbose_name='Course if head TA')),
            ],
            options={
                'verbose_name': 'Teaching Assistant',
                'verbose_name_plural': 'Teaching Assistants',
            },
        ),
        migrations.CreateModel(
            name='TAExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Exam')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.TA')),
            ],
            options={
                'verbose_name': 'Exam - TA Schedule',
                'verbose_name_plural': 'Exam - TA Schedules',
            },
        ),
        migrations.CreateModel(
            name='TASchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Classroom')),
            ],
            options={
                'verbose_name': 'TA Schedule',
                'verbose_name_plural': 'TA Schedules',
            },
        ),
    ]
