# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:25
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        # Rename field
        migrations.RenameField('TASchedule',
                               'classroom',
                               'ta'
                               ),
        # Change incorrectly assigned ForeignKey
        migrations.AlterField('TASchedule',
                              'ta',
                              models.ForeignKey('TA', on_delete=models.CASCADE, verbose_name='Teaching Assistant')
                              ),
    ]
